### ISSUE TITLE
Allow to type larger card names

### ISSUE THREAD

**Issue by idotj** [GeorgeYT9769/cardabase-app#5]
Currently the field "Card name" allow only 10 characters. Some supermarkets, shops, fidelity clubs, etc.. has larger names and it's not possible to type the full name in the field.

**Comment by GeorgeYT9769** [comment]
Yeah, but the name would go out of card space. Okay, I'll put smaller text there. Should there be smaller name for all cards or just depend on length?

**Comment by idotj** [comment]
As a Frontend developer, I faced this problem several times due to translations in buttons (some times in one language fits but when user changes to another language, the text overflows and breaks the width of the button).
The solution I use is to play with two CSS attributes: white-space and word-break.
I created an example for you here:
https://codepen.io/ipuntoj/pen/poMPXKJ

The third option will fit for you, so even if the user types a very long name, the text will automatically break and continue in the second line.

I hope this will work in the framework you are developing (I'm not an expert on Dart or Flutter)

**Comment by GeorgeYT9769** [comment]
Okay, thanks. But having the name being split into 2 lines isn't the best option yet.

**Comment by GeorgeYT9769** [comment]
Okay, thanks. I'll think about it.

**Comment by GeorgeYT9769** [comment]
Done! The card can now have 2 lines or approximately 20 characters. Due to this change, I had to redesign the 'card details' page, because the alert dialog was bugging. But at least now it looks cleaner and I can add additional info about the card later...

**Comment by idotj** [comment]
Great, I just downloaded the updated version and works as expected.
Thanks for the work :)

**Comment by idotj** [comment]
F-droid

**Comment by GeorgeYT9769** [comment]
Okay, thanks.
