### ISSUE TITLE
No apk for F-Droid reproducible build

### ISSUE THREAD

**Issue by linsui** [GeorgeYT9769/cardabase-app#6]
1.0.1 apk is not uploaded so F-Droid reproducible build failed. Could you please upload it?

**Comment by GeorgeYT9769** [comment]
I instantly deleted the 1.0.1 release because it had some issues, so it needs some fixes (I realized my mistake after making the new release).

Quick question to F-Droid, all I need to do is bump the version in pubspec.yml, upload files to GitHub, run the Action and apks that were built upload as a new release, and wait for F-Droid?

**Comment by linsui** [comment]
Yes, F-Droid will pick new versions automatically.

**Comment by GeorgeYT9769** [comment]
> Yes, F-Droid will pick new versions automatically.

Hey @linsui , my app got on F-Droid "Need updating" list. I don't know why, don't know what I did wrong... Could you help me?

**Comment by linsui** [comment]
https://github.com/GeorgeYT9769/cardabase-app/blob/v1.1.0/pubspec.yaml#L19 The version name and version code are not bumped so 1.1.0 is not picked up. Could you please bump them and release a new version?

**Comment by GeorgeYT9769** [comment]
Yeah, thanks.

**Comment by linsui** [comment]
We find that there is a `DependencyInfoBlock` in your APK.

It's a [Frosting](https://bi-zone.medium.com/easter-egg-in-apk-files-what-is-frosting-f356aa9f4d1) block in the signing block.

It's added by AGP and encrypted with the Google public key so it can't be read by anyone else except Google. You can read more about it [here](https://gitlab.com/fdroid/admin/-/issues/367) and [here](https://gitlab.com/fdroid/fdroidserver/-/issues/1056).

While this was added a while ago, we were only enforcing it for new apps, and recently we started scanning updates too.

Could you please disable it with the following code?

```
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

Thanks!

**Comment by GeorgeYT9769** [comment]
Sure! Thanks @linsui for help! 😁

**Comment by GeorgeYT9769** [comment]
The app is still on the list, even after 2 updates. I bumped the version, turned off the google metadata thing... @linsui

**Comment by licaon-kter** [comment]
@GeorgeYT9769 did you read  https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client yet?

**Comment by GeorgeYT9769** [comment]
Yes, new release was published 3 days ago and the list was updated a day ago. But I'll wait longer.

**Comment by licaon-kter** [comment]
Yes, hence a cycle started one day ago, see the monitor for its progress.

**Comment by licaon-kter** [comment]
The build server is just at your app now: https://monitor.f-droid.org/builds/running :)

**Comment by GeorgeYT9769** [comment]
Ohhh, thanks guys! You are the best! I was so confused 😅...
